name: Build Docker containers
on:
  push:
    branches:
      - custom
jobs:
  build-client:
    name: Build and push client/ Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine metadata
        run: |
          SHORT_COMMIT=$(echo $GITHUB_SHA | cut -c1-8)
          BUILD_INFO="parad0x3D-custom-${SHORT_COMMIT}"
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          echo "build_info=${BUILD_INFO}" >> $GITHUB_ENV
          echo "build_date=${BUILD_DATE}" >> $GITHUB_ENV

          echo "Build Info: ${BUILD_INFO}"
          echo "Build Date: ${BUILD_DATE}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        run: >
          docker buildx build --push
          --platform linux/amd64,linux/arm/v7,linux/arm64/v8
          --build-arg BUILD_INFO=${{ env.build_info }}
          --build-arg BUILD_DATE=${{ env.build_date }}
          --build-arg SOURCE_COMMIT=$GITHUB_SHA
          --build-arg DOCKER_REPO=ghcr.io/parad0x3dart/szurubooru-client
          -t "ghcr.io/parad0x3dart/szurubooru-client:latest"
          ./client

  build-server:
    name: Build and push server/ Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine metadata
        run: |
          SHORT_COMMIT=$(echo $GITHUB_SHA | cut -c1-8)
          BUILD_INFO="parad0x3D-custom-${SHORT_COMMIT}"
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          echo "build_info=${BUILD_INFO}" >> $GITHUB_ENV
          echo "build_date=${BUILD_DATE}" >> $GITHUB_ENV

          echo "Build Info: ${BUILD_INFO}"
          echo "Build Date: ${BUILD_DATE}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        run: >
          docker buildx build --push
          --platform linux/amd64,linux/arm/v7,linux/arm64/v8
          --build-arg BUILD_DATE=${{ env.build_date }}
          --build-arg SOURCE_COMMIT=$GITHUB_SHA
          --build-arg DOCKER_REPO=ghcr.io/parad0x3dart/szurubooru-server
          -t "ghcr.io/parad0x3dart/szurubooru-server:latest"
          ./server
